import streamlit as st

st.header("ABOUT")
st.subheader("World Happiness Report Overview:")
st.write("The World Happiness Report ranks countries based on how happy their citizens feel, measured through life evaluations from the Gallup World Poll. The report identifies six key factors that contribute to happiness and examines the influence of social, economic, and governance structures on well-being. It also includes a dystopian element—looking at how factors such as inequality, corruption, and lack of freedom can create a negative or dystopian environment for citizens, affecting their overall happiness.")
st.write("Key Factors in the Report:")
st.write("**GDP per capita**")
st.write("*Measures the economic wealth of a country, indicating the material standard of living. A higher GDP suggests better access to resources, affecting happiness positively.*")
st.write("**Healthy life expectancy**")
st.write("*Reflects how long people live in good health. The longer and healthier the life expectancy, the more likely people are to report greater life satisfaction.*")
st.write("**Social support**")
st.write("*Represents whether people feel they have reliable friends or family to rely on in times of need. Strong social connections are crucial for emotional resilience and overall happiness.*")
st.write("**Freedom to make life choices**")
st.write("*Indicates how free people feel to make decisions about their own lives, including career and lifestyle choices. Autonomy is linked to higher life satisfaction.*")
st.write("**Generosity**")
st.write("*Based on the extent to which people help others, such as making donations. Acts of kindness and helping others are associated with increased happiness, both for individuals and communities.*")
st.write("**Perceptions of corruption**")
st.write("*Measures how much people trust their government and institutions. Higher trust in public institutions and lower perceptions of corruption are linked to greater societal happiness.*")
st.write("")
st.write("**Dystopian Residual (Challenges affecting happiness)**")
st.write("While the six factors contribute to positive life satisfaction, the report also acknowledges that dystopian residuals—issues like corruption, inequality, political instability, and limited personal freedoms—can hinder happiness in many countries. These residuals can create negative experiences, such as:")
st.write("- Lack of trust in institutions (due to corruption or unfairness).")
st.write("- Economic inequality, where a large portion of the population struggles to meet basic needs.")
st.write("- Political oppression and lack of freedom, leading to reduced well-being.")
st.write("- Social alienation and weak community connections in places where individuals feel unsupported.")
st.write("These dystopian factors, although not always measurable directly, often distort the positive impacts of the six main factors and can significantly diminish overall happiness in certain regions or countries.")